services:
  bidding-rare-db:
    image: postgres
    restart: always
    container_name: bidding-rare-db
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuser
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: